[package]
name = "shv"
version = "0.1.1"
authors = ["Bryan Bugyi <bryanbugyi34@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
clap = "2.31.2"
env_logger = "0.7.0"
log = "0.4.8"
regex = "1.3.1"
tempfile = "3.1.0"
