[package]
name = "vshlog"
version = "0.1.0"
authors = ["Bryan Bugyi <bryanbugyi34@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.31.2"
env_logger = "0.7.0"
error-chain = "0.12.0"
log = "0.4.8"
